import time
from pathlib import Path

import cv2
import numpy as np
from pupil_apriltags import Detector


# The program expects four AprilTags positioned around the plate.
EXPECTED_TAG_IDS = [0, 1, 2, 3]

# Save generated plate coordinates beside this script.
BASE_DIR = Path(__file__).resolve().parent
COORDINATE_FILE = BASE_DIR / "latest_plate_scan.py"

# USB camera settings used during plate calibration.
CAMERA_INDEX = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30


# Converts the detector's floating-point tag center into integer image pixels.
def get_tag_center(tag):
    return int(tag.center[0]), int(tag.center[1])


# Returns the pixel halfway between two points.
def midpoint(p1, p2):
    return ((p1[0] + p2[0]) // 2, (p1[1] + p2[1]) // 2)


# Uses the four detected tag centers to estimate the plate center
# and the center of each food section.
# X and Y are camera-image pixels. The shared Z value is the distance
# measured by the ToF sensor in centimeters.
def calculate_plate_coordinates(tag_centers, plate_z_cm):
    p0 = tag_centers[0]
    p1 = tag_centers[1]
    p2 = tag_centers[2]
    p3 = tag_centers[3]

    # Average all four tag positions to estimate the plate's center.
    plate_center = (
        (p0[0] + p1[0] + p2[0] + p3[0]) // 4,
        (p0[1] + p1[1] + p2[1] + p3[1]) // 4,
    )

    # Estimate the center of each plate edge.
    # The physical tag order determines which edge maps to each section.
    edge_01 = midpoint(p0, p1)
    edge_12 = midpoint(p1, p2)
    edge_23 = midpoint(p2, p3)
    edge_30 = midpoint(p3, p0)

    # Place each section target halfway between the plate center
    # and its corresponding edge.
    section1_center = midpoint(plate_center, edge_01)
    section2_center = midpoint(plate_center, edge_12)
    section3_center = midpoint(plate_center, edge_23)
    section4_center = midpoint(plate_center, edge_30)

    return {
        "tags": {0: p0, 1: p1, 2: p2, 3: p3},
        "plate_center": plate_center,
        "plate_z_cm": plate_z_cm,
        "sections": {
            1: section1_center,
            2: section2_center,
            3: section3_center,
            4: section4_center,
        },
        "sections_3d": {
            1: (section1_center[0], section1_center[1], plate_z_cm),
            2: (section2_center[0], section2_center[1], plate_z_cm),
            3: (section3_center[0], section3_center[1], plate_z_cm),
            4: (section4_center[0], section3_center[1], plate_z_cm),
        },
    }


# Writes the detected plate coordinates as Python constants.
# feeding_cycle.py can later import the generated file to access
# the most recent plate-calibration result.
def save_coordinates(coordinates, coordinate_file=COORDINATE_FILE):
    coordinate_file = Path(coordinate_file)

    with open(coordinate_file, "w") as f:
        f.write("# Auto-generated by april_tag_with_value_update.py\n")
        f.write("# This file is updated after look-down calibration.\n\n")

        f.write(f"TAG_0 = {coordinates['tags'][0]}\n")
        f.write(f"TAG_1 = {coordinates['tags'][1]}\n")
        f.write(f"TAG_2 = {coordinates['tags'][2]}\n")
        f.write(f"TAG_3 = {coordinates['tags'][3]}\n\n")

        f.write(f"PLATE_CENTER = {coordinates['plate_center']}\n")
        f.write(f"PLATE_Z_CM = {coordinates['plate_z_cm']}\n\n")

        f.write(f"SECTION_1 = {coordinates['sections'][1]}\n")
        f.write(f"SECTION_2 = {coordinates['sections'][2]}\n")
        f.write(f"SECTION_3 = {coordinates['sections'][3]}\n")
        f.write(f"SECTION_4 = {coordinates['sections'][4]}\n\n")

        f.write(f"SECTION_1_3D = {coordinates['sections_3d'][1]}\n")
        f.write(f"SECTION_2_3D = {coordinates['sections_3d'][2]}\n")
        f.write(f"SECTION_3_3D = {coordinates['sections_3d'][3]}\n")
        f.write(f"SECTION_4_3D = {coordinates['sections_3d'][4]}\n")

    print(f"Coordinates saved to {coordinate_file}.")


# Opens the camera and waits until AprilTags 0, 1, 2, and 3
# are all visible in the same frame.
# After detecting the tags, the function reads the plate's distance
# from the ToF sensor and optionally saves the calculated coordinates.
def get_initial_plate_coordinates(
    camera_index=CAMERA_INDEX,
    timeout_seconds=20,
    save_to_file=True,
    show_preview=False,
):
    # The detector family must match the physical AprilTags on the plate.
    at_detector = Detector(families="tag36h11")

    cap = cv2.VideoCapture(camera_index)

    cap.set(cv2.CAP_PROP_FRAME_WIDTH, CAMERA_WIDTH)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, CAMERA_HEIGHT)
    cap.set(cv2.CAP_PROP_FPS, CAMERA_FPS)

    if not cap.isOpened():
        raise RuntimeError("Error: Could not open USB camera.")

    if show_preview:
        cv2.namedWindow("Plate Section Calibration", cv2.WINDOW_AUTOSIZE)

    print("AprilTag calibration started.")
    print("Waiting for tags 0, 1, 2, and 3...")

    start_time = time.time()

    try:
        while True:
            # Stop calibration if a complete tag set is not found in time.
            if time.time() - start_time > timeout_seconds:
                raise TimeoutError("Could not detect all four AprilTags in time.")

            success, frame = cap.read()

            if not success:
                raise RuntimeError("Failed to read frame from USB camera.")

            # AprilTag detection is performed on a grayscale image.
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            results = at_detector.detect(gray)

            # This dictionary contains recognized tags from the current frame.
            tag_centers = {}

            for r in results:
                tag_id = r.tag_id

                # Ignore tags that are not part of the plate calibration layout.
                if tag_id in EXPECTED_TAG_IDS:
                    cx, cy = get_tag_center(r)
                    tag_centers[tag_id] = (cx, cy)

                    if show_preview:
                        # Draw the tag outline, center, and ID for the operator.
                        corners = np.array(r.corners, dtype=np.int32)
                        cv2.polylines(frame, [corners], True, (0, 255, 0), 2)
                        cv2.circle(frame, (cx, cy), 5, (0, 0, 255), -1)
                        cv2.putText(
                            frame,
                            f"ID {tag_id}",
                            (cx + 8, cy - 8),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.5,
                            (0, 255, 0),
                            2,
                        )

            # All four tags must be visible in this same camera frame.
            # Partial detections are not saved between frames.
            if all(tag_id in tag_centers for tag_id in EXPECTED_TAG_IDS):
                print("All four AprilTags detected.")
                print("Reading z-distance from ToF sensor...")

                # Delay the ToF import until right here, to avoid GPIO mode conflicts
                # before the scan actually needs I2C / board / busio.
                from tof_sensor import get_single_tof_distance_and_close

                # Average five measurements for a steadier plate-height value.
                plate_z_cm = get_single_tof_distance_and_close(samples=5)

                print(f"Plate z-distance: {plate_z_cm} cm")
                print("ToF sensor closed after z reading.")

                coordinates = calculate_plate_coordinates(
                    tag_centers,
                    plate_z_cm,
                )

                if save_to_file:
                    save_coordinates(coordinates)

                return coordinates

            if show_preview:
                cv2.imshow("Plate Section Calibration", frame)

                # Press Q to stop an interactive calibration preview.
                if cv2.waitKey(1) & 0xFF == ord("q"):
                    raise KeyboardInterrupt("Calibration stopped by user.")

            # Prevent the camera loop from running at full CPU speed.
            time.sleep(0.01)

    finally:
        # Always release the USB camera, including after an exception.
        cap.release()

        if show_preview:
            cv2.destroyAllWindows()