-- AlterTable
ALTER TABLE "User" ADD COLUMN "breakfastTime" TEXT NOT NULL DEFAULT '08:00';
ALTER TABLE "User" ADD COLUMN "lunchTime" TEXT NOT NULL DEFAULT '12:30';
ALTER TABLE "User" ADD COLUMN "dinnerTime" TEXT NOT NULL DEFAULT '18:00';
